Repository slide-todo/slide-todo, pull requests merged in 2024-07, with the labels that each got.

#14 lint check 추가
  .github/workflows/line-check.yml
  app/page.tsx
Labels: Github Action

#15 feat: Button 컴포넌트 구현
  components/Buttons/Button.tsx
Labels: 공용 컴포넌트

#18 feat: input 컴포넌트 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/epic_issue_template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task_issue_template.md
  .github/workflows/lint-check.yml
  assets/svgs/ArrowDown.tsx
  assets/svgs/EyeFilledIcon.tsx
  assets/svgs/EyeSlashFilledIcon.tsx
  components/Input/TextAndPasswordInput.tsx
  package-lock.json
  package.json
  styles/globals.css
Labels: 공용 컴포넌트

#19 Components/select
  assets/svgs/.gitkeep
  components/Input/MixedInput.tsx
  components/Input/Selector.tsx
Labels: 공용 컴포넌트

#22 feat: 공통 컴포넌트 side-menu 구현
  app/layout.tsx
  app/page.tsx
  assets/svgs/ArrowDown.tsx
  assets/svgs/Profile.tsx
  assets/svgs/flag.svg
  assets/svgs/home.svg
  assets/svgs/logo-icon.svg
  assets/svgs/logo.svg
  assets/svgs/plus-blue.svg
  assets/svgs/plus.svg
  assets/svgs/sideFoldButton.svg
  components/Buttons/Button.tsx
  components/Input/MixedInput.tsx
  components/Input/Selector.tsx
  components/SideMenu/SideMenu.tsx
  styles/globals.css
Labels: 공용 컴포넌트

#29 Refactor: Button 컴포넌트 코드리뷰 반영
  components/Buttons/Button.tsx
  components/SideMenu/SideMenu.tsx
Labels: 공용 컴포넌트, 리뷰반영

#32 fix: 버튼 기본 스타일링 미적용분 적용
  assets/svgs/Kebab.tsx
  components/Buttons/Button.tsx
Labels: bug

#45 styles: scrollbar 스타일링
  styles/globals.css
Labels: style

#48 feat: 공통 컴포넌트 filter 구현
  app/page.tsx
  assets/svgs/PlusBlue.tsx
  assets/svgs/index.ts
  components/Filter/Filter.tsx
  components/ListTodo/ListTodo.tsx
  components/Popup/ConfirmPopup.tsx
  components/RecentlyTodo/RecentlyTodo.tsx
  components/SideMenu/SideMenu.tsx
Labels: 공용 컴포넌트

#50 feat: Counting 컴포넌트 구현
  components/Counting/Counting.tsx
Labels: 공용 컴포넌트

#51 feat:Plugin컴포넌트 구현 및 Selector, mixedInput 부분 수정
  components/Input/MixedInput.tsx
  components/Input/Selector.tsx
  components/Plugin/Plugin.tsx
  styles/globals.css
Labels: 공용 컴포넌트

#106 fix:link 슬리드 투두 로 변경
  app/(auth)/signin/page.tsx
Labels: 발견된 이슈

#113 Issue/modal
  .env
  app/(auth)/signup/page.tsx
  app/(pages)/goals/[goalId]/page.tsx
  app/(pages)/note/write/[todoId]/page.tsx
  app/api/auth/[...nextauth]/route.ts
  components/CardNote/CardNote.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalBody.tsx
  components/RecentlyTodo/RecentlyTodo.tsx
  components/SideMenu/SideMenu.tsx
  hooks/useListTodo.ts
  lib/api/api.ts
  lib/api/auth.ts
  lib/api/axios.ts
  lib/api/fileUpload.ts
  package-lock.json
  package.json
  queries/query.ts
Labels: 발견된 이슈

#118 Sidemenu 업데이트, 레이아웃 이슈
  app/(pages)/goals/[goalId]/page.tsx
Labels: 발견된 이슈

#121 fix:공백문자에 tag 포함되던 문제 해결
  .env
  app/(pages)/note/write/[todoId]/page.tsx
  utils/extractTextFromHtml.ts
Labels: 발견된 이슈

#123 feat: note 삭제 추가
  app/(pages)/goals/[goalId]/page.tsx
  app/(pages)/todolist/page.tsx
  components/ListTodo/ListTodo.tsx
  components/Popover/Popover.tsx
  hooks/useListTodo.ts
  types/Todo.ts
Labels: 발견된 이슈

#128 fix: 노트모아보기 loading처리
  app/(pages)/notes/[goalId]/page.tsx
Labels: 발견된 이슈

#131 fix:모달 초기값 명시 및 컨펌팝업 사이즈 조정
  app/(pages)/goals/[goalId]/page.tsx
  components/CardGoal/CardGoal.tsx
  components/Modal/Modal.tsx
  components/Popup/ConfirmPopup.tsx
Labels: 발견된 이슈

#133 fix: localStorage에 token 저장
  lib/api/axios.ts
Labels: 발견된 이슈

#136 Issue/note write
  app/(pages)/note/write/[todoId]/page.tsx
  components/ContentEditor/ContentEditor.tsx
  components/ContentEditor/CustomQuill.css
  components/Embeded/Embeded.tsx
  components/LinkBar/LinkBar.tsx
  utils/invalidateInput.test.js
  utils/invalidateInput.ts
Labels: 발견된 이슈

#138 feat:404페이지 구현
  app/not-found.tsx
  assets/svgs/404.tsx
  assets/svgs/index.ts
Labels: 페이지, 발견된 이슈
